language: python
cache: pip
python:
  - "3.6"
  - "3.5"
install:
  - pip install -r requirements_dev.txt
script:
#  - flake8 # Kill for now, copy and pasted code has to many issues
  - python -m pytest tests/
